name: Greeting

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greet on pull request
        if: github.event_name == 'pull_request'
        uses: actions/hello-world-javascript-action@v1.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Hello 👋, Thank you for your contribution!, this is the awsome Geographic Garden of Kolding"
